{% set name = "google-cloud-talent" %}
{% set version = "2.10.1" %}
{% set sha256 = "5e06508237026f12f1ca266262f7dc4a8cc2e9935bdecaec9018728c9ce0b585" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip >=18.1
  run:
    - python >=3.6
    - google-api-core-grpc >=1.26.0,<2.0.0dev
    - proto-plus >=1.15.0
    - packaging >=14.3

test:
  imports:
    - grpc
    - google.cloud.talent
    - google.cloud.talent_v4beta1
    - google.cloud.talent_v4

about:
  home: https://github.com/googleapis/python-talent
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google Cloud Talent Solution API client library
  description: "Cloud Talent Solution API provides the capability to create, read, update, and delete job postings, as well as search jobs based on keywords and filters.\nSee the [quick start guide](https://googleapis.dev/python/talent/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/talent/latest/index.html
  dev_url: https://github.com/googleapis/python-talent

extra:
  recipe-maintainers:
    - parthea
